### ISSUE TITLE
Add Animation 

### ISSUE THREAD

**Issue by ShivamDecodes** [ShivamDecodes/WebsiteAnimation#1]
[Readme.nd.txt](https://github.com/ShivamDecodes/WebsiteAnimation/files/7270997/Readme.nd.txt)
![Help Image](https://user-images.githubusercontent.com/87795454/135706685-f829c0ac-b5ea-4bf9-aa9f-160f32f6f8d9.png)

**Comment by MoveFl** [comment]
I can do it!

**Comment by ShivamDecodes** [comment]
> I can do it!

OK DO IT...
