### ISSUE TITLE
Add Fundamental Calculator Algorithm

### ISSUE THREAD

**Issue by ShivamDecodes** [ShivamDecodes/WebsiteAnimation#8]
### HACKTOBERFEST SPECIAL ISSUES

**Add Calculator Algo Separately For:-**

_1. Sum
2. Difference
3. Product
4. Quotient
5. Average_

`easy to grab issues` @ShivamDecodes

**Comment by ShivamDecodes** [comment]
Yes These Issues Easy But Simultaneously Essential For The Project.

**Comment by MoveFl** [comment]
Ham Kar Den kya? 💯

**Comment by algo-byte** [comment]
Hey @ShivamDecodes do you want the logic to be written in js?

**Comment by ShivamDecodes** [comment]
> Ham Kar Den kya? 💯

Kar Lo...

**Comment by algo-byte** [comment]
ohk sure thanks!!

**Comment by ShivamDecodes** [comment]
> Hey @ShivamDecodes do you want the logic to be written in js?

No Sorry bro Only java...
But I can provide you tasks for JS Too..

**Comment by ShivamDecodes** [comment]
> ohk sure thanks!!

Hey That was not for you it was for movefl...
wait i am assigning you some tasks...
what can you do in js?
