### ISSUE TITLE
Add Logos Of All Company Sponsoring HacktoberFest 2021 Using Code Algo

### ISSUE THREAD

**Issue by ShivamDecodes** [ShivamDecodes/WebsiteAnimation#9]
### HACKTOBERFEST SPECIAL ISSUES

**Add Logo Algo For:-**

_1. indeed
2. MLH
3. Gremlin
4. Progate
5. Stripe
6. Gitcoin
7. cloudFlare
8. MongoDB
9. Mattermost
10. RaiseDev
11. FreshWork
12. Cockroach Labs
13. Open Collective
14. DEV
15. intel
16. CircleCI
17. Digital Ocean_

`easy to grab issues` @ShivamDecodes

**Comment by MoveFl** [comment]
I want to do it.... 🥇

**Comment by ShivamDecodes** [comment]
> I want to do it.... 🥇

Bana De Bhai 👍
